# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "price-worker"
main = "src/index.js"
compatibility_date = "2025-11-15"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "price-db"
database_id = "fff66b71-d33a-4669-bc98-4cfbed1647fe"

# KV Namespace binding for caching
[[kv_namespaces]]
binding = "PRICE_CACHE"
id = "3d3d63b744884bc3a14c44fedb581151"

# R2 Logs binding
[[r2_buckets]]
binding = "LOGS"
bucket_name = "price-worker-logs"

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# placement = { mode = "smart" }

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

